USE PETS_DB;

CREATE TABLE IF NOT EXISTS Pets(
Pet_ID INT AUTO_INCREMENT PRIMARY KEY,
Species VARCHAR(20) NOT NULL,
Pet_Name VARCHAR(20) NOT NULL,
Breed VARCHAR(20) NOT NULL,
Age INT NOT NULL,
Price INT NOT NULL);

CREATE TABLE IF NOT EXISTS Customers(
Customer_ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(25) NOT NULL,
Contact VARCHAR(15) NOT NULL,
Email VARCHAR(25) NOT NULL ,
City VARCHAR(15) NOT NULL);

CREATE TABLE IF NOT EXISTS Purchase (
Transaction_ID INT AUTO_INCREMENT PRIMARY KEY,
CustomerID INT ,
Customer_Name VARCHAR(25),
PetID INT ,
PetName VARCHAR(20) ,
Species VARCHAR(25) ,
Amount_Payed VARCHAR(10) ,
FOREIGN KEY(CustomerID) REFERENCES Customers(Customer_ID),
FOREIGN KEY(PetID) REFERENCES Pets(Pet_ID)
);

-- ALTER TABLE Purchase
-- ADD COLUMN Payment_Method VARCHAR(25),
-- ADD COLUMN Payment_Date_and_Time VARCHAR(60);

CREATE TABLE IF NOT EXISTS Products (
Product_ID INT AUTO_INCREMENT PRIMARY KEY,
Product_Name VARCHAR(50) NOT NULL,
Category VARCHAR(20),
Price INT NOT NULL,
Stock INT NOT NULL
);

ALTER TABLE Purchase
ADD COLUMN ProductID INT NULL,
ADD COLUMN ProductName VARCHAR(50) NULL,
ADD COLUMN Quantity INT DEFAULT 1,
ADD CONSTRAINT fk_product FOREIGN KEY (ProductID) REFERENCES Products(Product_ID);



SELECT*FROM Pets;
SELECT*FROM Customers;
SELECT*FROM Purchase;



-- Run this entire block in your MySQL client:
USE PETS_DB;

-- Disable foreign key checks
SET FOREIGN_KEY_CHECKS = 0;

-- Clear tables in reverse dependency order
TRUNCATE TABLE Purchase;
TRUNCATE TABLE Products;
TRUNCATE TABLE Pets;
TRUNCATE TABLE Customers;

-- Reset auto-increment counters
ALTER TABLE Purchase AUTO_INCREMENT = 1;
ALTER TABLE Products AUTO_INCREMENT = 1;
ALTER TABLE Pets AUTO_INCREMENT = 1;
ALTER TABLE Customers AUTO_INCREMENT = 1;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- Verify tables are empty
SELECT COUNT(*) FROM Purchase;
SELECT COUNT(*) FROM Products;
SELECT COUNT(*) FROM Pets;
SELECT COUNT(*) FROM Customers;

