USE PETS_DB;

CREATE TABLE IF NOT EXISTS Pets(
Pet_ID INT AUTO_INCREMENT PRIMARY KEY,
Species VARCHAR(20) NOT NULL, 
Pet_Name VARCHAR(20) NOT NULL, 
Breed VARCHAR(20) NOT NULL, 
Age INT NOT NULL,
Price INT);

CREATE TABLE IF NOT EXISTS Customers(
Customer_ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(25) NOT NULL,
Contact VARCHAR(15) NOT NULL,
Email VARCHAR(25) NOT NULL ,
City VARCHAR(15) NOT NULL);

CREATE TABLE IF NOT EXISTS Purchase (
Transaction_ID INT AUTO_INCREMENT PRIMARY KEY,
CustomerID INT ,
Customer_Name VARCHAR(25),
PetID INT ,
PetName VARCHAR(20) ,
Species VARCHAR(25) ,
Amount_Payed VARCHAR(10) ,
FOREIGN KEY(CustomerID) REFERENCES Customers(Customer_ID),
FOREIGN KEY(PetID) REFERENCES Pets(Pet_ID)
);
SELECT*FROM Pets;
SELECT*FROM Customers;
SELECT*FROM Purchase;


