USE PETS_DB;
CREATE TABLE IF NOT EXISTS Pets(
ID INT AUTO_INCREMENT PRIMARY KEY,
Species VARCHAR(20) NOT NULL, 
Pet_Name VARCHAR(20) NOT NULL, 
Breed VARCHAR(20) NOT NULL, 
Age INT NOT NULL);

CREATE TABLE IF NOT EXISTS Owner(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(25) NOT NULL,
CONTACT VARCHAR(15) NOT NULL,
EMAIL VARCHAR(25) NOT NULL
);

SELECT*FROM Pets;
SELECT*FROM Owner;

